#' Reclustering Analysis
#'
#' Performs reclustering and basic visualization
#' of a subsetted Seurat object subset.
#' Subsets are determined based on cell groups.
#'
#' @param title1 Name of cell type(s) being reclustered. This information
#' is used for filenames generated by reclustering analysis.
#' @param so An object of class Seurat.
#' @param rc_type Data set type being reclustered (either "GEX" or "Mult").
#' @param ct_col Column containing cell type information.
#' @param ct Character strings separated by vertical bars "|"
#' indicating cell types to factor in reclustering.
#' The provided Seurat object is then subsetted to include
#' only clusters from the provided group names.
#' @param slot1 Assay from Seurat object subset to use (ex. "RNA").
#' @param md_list A vector of character strings indicating metadata
#' columns for overlaying on a loadings plot.
#' @param prop_list Subset of md_list to use for stratifying cell type
#' proportion columns.
#' @param dim1 Number of dimensions to use in PCA.
#' @param batch_cor Should Harmony based batch correction be performed?
#' This parameter is automatically set to TRUE for multiome datasets.
#' @param cor_col Variables to account for in batch correction.
#' @param res1 Clustering resolution to use for final cluster determination.
#' @param h_w Numeric value for heatmap width (passed to ComplexHeatmap).
#' @param h_h Numeric value for heatmap height (passed to ComplexHeatmap).
#' @param fs_c Numeric value for column fontsize (passed to ComplexHeatmap).
#' @param fs_r Numeric value for row fontsize (passed to ComplexHeatmap).
#' @param cl_c Cluster columns?
#' @param cl_r Cluster rows?
#' @param rot_c Rotation of column names.
#' @param col1 Gradient color scheme to use
#' (must be exactly 4 colors in length).
#' @return A reclustered Seurat Object with summary plots, proportion tables,
#' and marker gene lists.
#' @examples
#'
#' # d_recluster <- sc_recluster(
#' #   title1 = "basal",
#' #   so = d_gene,
#' #   rc_type = "GEX",
#' #   ct_col = "CellType",
#' #   ct = "Bas|Cyc|Sup",
#' #   slot1 = "RNA",
#' #   md_list = c("Code", "Airway", "Batch"),
#' #   prop_list = c("Code", "Airway"),
#' #   dim1 = 30,
#' #   cor_col = c("Batch", "Code"),
#' #   col1 = col_hmap
#' # )
#'
#' @export
sc_recluster <- function(
  title1,
  so,
  rc_type,
  ct_col,
  ct,
  slot1 = "RNA",
  md_list,
  prop_list,
  dim1 = 50,
  batch_cor = TRUE,
  cor_col,
  res1 = 0.5,
  h_w = 38,
  h_h = 18,
  fs_c = 6,
  fs_r = 9,
  cl_c = FALSE,
  cl_r = FALSE,
  rot_c = 45,
  col1 = col_grad(scm = 3)
) {
  # Load objects
  d <- so
  ctn <- ct_col
  ctf <- ct

  # Reclustering of traditional scRNA-Seq data
  if(rc_type == "GEX") { # nolint
    SeuratObject::DefaultAssay(d) <- slot1
    # subset
    d <- d[, grepl(ctf, as.character(d@meta.data[[ctn]]))]
    # Re-run dimension reduction on object subset
    options(future.globals.maxSize = 10000 * 1024 ^ 2)
    d <- Seurat::SCTransform(d, new.assay.name = "sct")
    # Run PCA
    d <- Seurat::RunPCA(d)
    d_pca <- sc_pca_plot( # nolint
      so = d,
      md_list = c(md_list, ct_col),
      red1 = "pca"
    )
    ## Run Harmony if batch effect exists
    if(batch_cor == TRUE) { # nolint
      d <- harmony::RunHarmony(
        d,
        assay.use = "sct",
        group.by.vars = cor_col,
        reduction.use = "pca",
        reduction.save = "pca.cor",
        project.dim = FALSE
      )
      plot_var_feat <- Seurat::VariableFeaturePlot(
        d,
        assay = "sct"
      )
      plot_elbow <- Seurat::ElbowPlot(
        d,
        reduction = "pca.cor",
        ndims = dim1
      )
      # Run UMAP
      Seurat::Idents(d) <- ct_col
      d <- Seurat::RunUMAP(
        object = d,
        reduction = "pca.cor",
        dims = 1:dim1,
        n.components = 3
      )
    }
    if(batch_cor == FALSE) { # nolint
      plot_var_feat <- Seurat::VariableFeaturePlot(
        d,
        assay = "sct"
      )
      plot_elbow <- Seurat::ElbowPlot(
        d,
        reduction = "pca",
        ndims = dim1
      )
      # Run UMAP
      Seurat::Idents(d) <- ct_col
      d <- Seurat::RunUMAP(
        object = d,
        reduction = "pca",
        dims = 1:dim1,
        n.components = 3
      )
    }
    SeuratObject::DefaultAssay(d) <- "sct"
    d <- Seurat::FindNeighbors(
      d,
      reduction = "umap",
      dims = 1:3,
      verbose = TRUE
    )
    d <- Seurat::FindClusters(
      d,
      cluster.name = "recluster",
      resolution = res1
    )
    d_umap1 <- sc_umap_panel( # nolint
      d,
      c(ct_col, md_list, "recluster"),
      "umap"
    )
    ## Reclustering Performance
    d1qc_pre <- Seurat::VlnPlot(
      object = d,
      features = c(
        "nFeature_RNA",
        "nCount_RNA",
        "percent.mt",
        "nCount_ATAC",
        "TSS.enrichment",
        "nucleosome_signal"
      ),
      layer = "counts",
      ncol = 4,
      pt.size = 0.2
    )

    # Marker gene heatmap
    d_hmap <- sc_top10_marker_heatmap_rc( # nolint
      title1 = title1,
      sorc = d,
      asy = "GEX",
      slot1 = "sct",
      cl_var = "recluster",
      h_w = h_w,
      h_h = h_h,
      fs_c = fs_c,
      fs_r = fs_r,
      cl_c = cl_c,
      cl_r = cl_r,
      rot_c = rot_c,
      col1 = col1
    )
    # Cluster Proportions
    fun_predict_prop <- function(
      x,
      c,
      md
    ) {
      data_pred_prop2 <- setNames(
        dplyr::count(
          x,
          .data[[c]] # nolint
        ),
        c(c, "Total Cells")
      )
      data_pred_prop <- dplyr::count(
        x,
        x[, c(md, c)]
      )
      data_pred_prop <- dplyr::left_join(
        data_pred_prop,
        data_pred_prop2,
        by = c
      )
      data_pred_prop[["Proportion"]] <- round(
        data_pred_prop$n /
          data_pred_prop$`Total Cells`,
        digits = 3
      )
      return(data_pred_prop) # nolint
    }
    d <- SeuratObject::AddMetaData(
      d,
      gsub("_.*", "", d@meta.data[["Code"]]),
      col.name = "Code1"
    )
    cnt_prop <- fun_predict_prop(
      d@meta.data,
      "recluster",
      c(prop_list)
    )
  }
  if(rc_type == "Mult") { # nolint
    # Re-run SCTransform and batch correct GEX data;
    # leave corrected ATAC data as-is
    # Normalization
    ## GEX
    Seurat::DefaultAssay(d) <- slot1
    # subset
    d <- d[
      ,
      grepl(
        ctf,
        as.character(d@meta.data[[ctn]])
      )
    ]
    d_umap1 <- sc_umap_panel( # nolint
      d,
      c(
        ctn, c("Code", "Airway", "Batch")
      ),
      "wnn.umap"
    )
    options(future.globals.maxSize = 10000 * 1024 ^ 2)
    d <- Seurat::FindVariableFeatures(
      d,
      selection.method = "vst",
      nfeatures = 3000
    )
    d <- Seurat::SCTransform(
      d,
      new.assay.name = "sct"
    )
    d <- Seurat::RunPCA(d)
    d <- harmony::RunHarmony(
      d,
      assay.use = "sct",
      group.by.vars = cor_col,
      reduction.use = "pca",
      reduction.save = "pca_cor",
      project.dim = FALSE
    )
    plot_var_feat <- Seurat::VariableFeaturePlot(
      d,
      assay = "sct"
    )
    plot_elbow <- Seurat::ElbowPlot(
      d,
      reduction = "pca_cor",
      ndims = dim1
    )
    d_pca <- sc_pca_plot( # nolint
      d,
      c(ctn, md_list),
      "pca_cor"
    )
    ## WNN
    d <- Seurat::FindMultiModalNeighbors(
      d,
      reduction.list = list(
        "pca_cor",
        "ufy.peaks.corrected"
      ),
      dims.list = list(1:dim1, 2:dim1)
    )
    d <- Seurat::RunUMAP(
      d,
      nn.name = "weighted.nn",
      reduction.name = "re_wnn_umap",
      reduction.key = "wnnUMAP_",
      n.components = 3
    )
    d <- Seurat::FindNeighbors(
      d,
      reduction = "re_wnn_umap",
      dims = 1:3,
      verbose = TRUE
    )
    d <- Seurat::FindClusters(
      d,
      graph.name = "wsnn",
      cluster.name = "recluster",
      algorithm = 3,
      verbose = TRUE,
      resolution = res1
    )
    d@meta.data[["recluster"]] <- factor(
      as.numeric(d@meta.data[["recluster"]]),
      levels = seq.int(
        1,
        length(unique(as.numeric(d@meta.data[["recluster"]]))),
        1
      )
    )
    ## Visualize Clusters
    d_umap1 <- sc_umap_panel( # nolint
      d,
      c(
        ctn, md_list, "recluster"
      ),
      "re_wnn_umap"
    )
    ## Reclustering Performance
    d1qc_pre <- Seurat::VlnPlot(
      object = d,
      features = c(
        "nFeature_RNA",
        "nCount_RNA",
        "percent.mt",
        "nCount_ATAC",
        "TSS.enrichment",
        "nucleosome_signal"
      ),
      layer = "counts",
      ncol = 4,
      pt.size = 0.2
    )
    # Marker gene heatmap
    d_hmap <- sc_top10_marker_heatmap_rc( # nolint
      title1 = title1,
      sorc = d,
      asy = "GEX",
      slot1 = "sct",
      cl_var = "recluster",
      h_w = h_w,
      h_h = h_h,
      fs_c = fs_c,
      fs_r = fs_r,
      cl_c = cl_c,
      cl_r = cl_r,
      rot_c = rot_c,
      col1 = col1
    )
    # Cluster Proportions
    fun_predict_prop <- function(
      x,
      c,
      md
    ) {
      data_pred_prop2 <- setNames(
        dplyr::count(
          x,
          .data[[c]] # nolint
        ),
        c(c, "Total Cells")
      )
      data_pred_prop <- dplyr::count(
        x,
        x[, c(md, c)]
      )
      data_pred_prop <- dplyr::left_join(
        data_pred_prop,
        data_pred_prop2,
        by = c
      )
      data_pred_prop[["Proportion"]] <- round(
        data_pred_prop$n /
          data_pred_prop$`Total Cells`,
        digits = 3
      )
      return(data_pred_prop) # nolint
    }
    if(is.null(d@meta.data[["Code"]])) { # nolint
      d <- SeuratObject::AddMetaData(
        d,
        gsub("_.*", "", d@meta.data[["Code"]]),
        col.name = "Code1"
      )
    }
    cnt_prop <- fun_predict_prop(
      d@meta.data,
      "recluster",
      c(prop_list)
    )
  }
  return(
    list = c(
      "data" = d,
      "pca_panel" = d_pca,
      "pca_feat" = plot_var_feat,
      "pca_elbow" = plot_elbow,
      "umap_panel" = d_umap1,
      "hmap_top10" = d_hmap,
      "ct_counts" = cnt_prop,
      "qc_vio" = d1qc_pre
    )
  )
}
