#' Volcano Plot
#'
#' Generates a volcano plot from a formatted DGEA results data frame for
#' a chosen comparison and/or cell type.
#'
#' @param l_deg A data frame of DGEA results in the same format as
#' outputs generated by sc_diff.
#' @param ct A character string pattern for matching to specific cell types.
#' @param comp_name Comparison name, provided as a character string.
#' @param cl_col Optional variable name for coloring significant
#' points based on class.
#' @param alt_col Optional named vector of colors for manually
#' specifying colors is cl_col is provided.
#' @param comp_filt Filter data by comparison name.
#' @param gene_name Column name containing gene or motif names.
#' @param filt_lab (optional) Select labels to include on plot.
#' @param diff_col Column name containing effect size.
#' @param p_col Column name containing adjust p-values.
#' @param p_cut Numeric value for p-value cutoff to indicate significance.
#' @param f_cut Fold change cutoff indicating high effect size.
#' @param f_lim Numeric value for fold change limits on the x-axis.
#' @param y_limit Upper-bound -log10 p-value to display on the y-axis.
#' @param x_title X-axis legend title, provided as a character string.
#' @param pt_size Numeric value for point size.
#' @param lab_size Numeric value for label size.
#' @param mx_overlap Numeric value passed to EnhancedVolcano for
#' calculating the maximum number of overlapping labels to display.
#' @param ret_input Return plot input instead of plot.
#' @return A volcano plot for the chosen cell type and treatment comparison.
#' @examples
#'
#' # p_vol <- sc_volcano(
#' #   l_deg = diff.output.activity,
#' #   ct = "1.Secretory",
#' #   comp_name = "KO vs. Control",
#' #   gene_name = "gene",
#' #   filt_lab = grepl("NKX|FOXA", diff.output.activity[["gene"]]),
#' #   diff_col = "avg_diff",
#' #   p_col = "p_val_adj",
#' #   p_cut = 0.005,
#' #   f_cut = 0.25,
#' #   f_lim = 6,
#' #   y_limit = 100,
#' #   x_title = "x-axis title"
#' # )
#'
#' @export
sc_volcano <- function( # nolint
  l_deg,
  ct = NULL,
  comp_name = NULL,
  comp_filt = FALSE,
  gene_name = "GENE",
  filt_lab = NULL,
  diff_col = "log2FC",
  cl_col = NULL,
  alt_col = NULL,
  p_col = "H.qval",
  p_cut = 0.05,
  f_cut = 0.25,
  f_lim = 5,
  y_limit = 50,
  x_title = NULL,
  pt_size = 2,
  lab_size = 4,
  mx_overlap = 18,
  ret_input = FALSE
) {
  #---- Format data ----
  ld <- l_deg
  if (!is.null(comp_name)) ld <- ld[ld[["Comparison"]] == comp_name, ]
  if (!is.null(ct)) ld <- ld[ld[["CellType"]] == ct, ]
  if (!is.null(cl_col)) {
    ld[[cl_col]] <- ifelse(
      ld[[p_col]] < p_cut,
      ld[[cl_col]],
      "NS"
    )
    if (is.null(alt_col)) {
      ld[["Class"]] <- factor(
        ld[[cl_col]],
        levels = c(
          gtools::mixedsort(
            unique(ld[[cl_col]])[unique(ld[[cl_col]]) != "NS"]
          ),
          "NS"
        )
      )
    }
    if (!is.null(alt_col)) {
      ld[["Class"]] <- factor(
        ld[[cl_col]],
        levels = names(alt_col)
      )
    }
    if (is.null(alt_col)) {
      cols1 <- data.frame(
        "Class" = levels(ld[["Class"]]),
        "Color" = c(col_univ()[1:(length(levels(ld[["Class"]])) - 1)], "grey75") # nolint
      )
    }
    if (!is.null(alt_col)) {
      cols1 <- setNames(stack(alt_col), c("Color", "Class"))
    }
    ld <- dplyr::left_join(ld, cols1, by = "Class")
  }
  #---- Create Plot ----
  v <- EnhancedVolcano::EnhancedVolcano(
    ld,
    x = diff_col,
    y = p_col,
    pCutoff = p_cut,
    FCcutoff = f_cut,
    lab = ld[[gene_name]],
    selectLab = if (!is.null(filt_lab)) filt_lab else NULL,
    colCustom = if (!is.null(ld[["Class"]])) {
      setNames(ld[["Color"]], ld[["Class"]])
    } else {
      NULL
    },
    legendLabels = if (!is.null(ld[["Class"]])) {
      NULL
    } else {
      c("NS", "Fold Change", "p-value", "FC+P")
    },
    col = if (!is.null(ld[["Class"]])) {
      NULL
    } else {
      ggsci::pal_npg("nrc")(10)[c(4, 3, 5, 8)]
    },
    pointSize = pt_size,
    labSize = lab_size,
    max.overlaps = mx_overlap,
    subtitle = NULL,
    caption = NULL,
    cutoffLineType = "twodash",
    legendLabSize = 12,
    labFace = "bold",
    colAlpha = 0.6,
    legendIconSize = 4,
    border = "full",
    borderWidth = 1.5,
    legendPosition = 'bottom', # nolint
    drawConnectors = TRUE,
    typeConnectors = "open",
    widthConnectors = 0.35,
    colConnectors = "grey75",
    min.segment.length = ggplot2::unit(
      1,
      "mm"
    )
  ) +
    sc_theme1() + # nolint
    ggplot2::labs(
      color = "Key",
      x = x_title,
      y = paste("-log10 P-value (FDR)")
    ) +
    ggplot2::ggtitle(
      paste(
        comp_name,
        sep = " "
      )
    ) +
    ggplot2::theme(
      plot.margin = ggplot2::unit(c(.2, .2, .2, .2), "cm")
    ) +
    ggplot2::coord_cartesian(xlim = c(-f_lim, f_lim),
                             ylim = c(0, y_limit)) +
    ggplot2::scale_x_continuous(
      breaks = seq(-f_lim, f_lim, (f_lim / 4))
    )
  if (ret_input == FALSE) return(v) else return(ld) # nolint
}
